# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luis Castro
email: luiscastroem@domain.com
description: I'm a Full-Stack Developer and computer engineer currently traveling the world. In my work, I combine 3 basic principles User Experience, Beauty and Purpose. I have 5+ years doing Software Development and have completed more than 17 projects (managed 4 of them) in 2 continents. I make webapps that work fast, are easy to use, persuasive, relevant to the customer and fit in the business environment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://luiscastro.co" # the base hostname & protocol for your site
twitter_username: castrolem
github_username:  castrolem

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
