# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luis Castro • Full Stack Developer
email: luiscastroem@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Full Stack Developer that makes products that work fast, are easy to use, persuasive, relevant to the customer and fit in the business environment.
  Currently working from Barcelona, Spain.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://luiscastro.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: castrolem
github_username:  castrolem

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
plugins_dir: ./_plugins

# used for the contact button in _layouts/resume.html
resume_contact_email:           "luiscastroem@gmail.com"

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/castrolem"
  resume_twitter_url:           "http://twitter.com/castrolem"
  resume_linkedin_url:          "https://www.linkedin.com/in/castrolem"

jekyll_xml:
  - data: podcast
    source: https://anchor.fm/s/da014d4/podcast/rss
    cache: true
